name = "game-project"
main = "worker.js"
compatibility_date = "2024-12-30"

[build]
command = "npm run build"

[site]
bucket = "./dist"

[env.production]
name = "game-project"
route = "game-project.shugarfreestudio.workers.dev/*"